### ISSUE TITLE
Heater temperatures transfered to image metadata?

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/rac-extract-payload#119]
I think we discussed that the heater temperatures 'HTR1A', 'HTR1B', etc, that is now in the HTR.csv file would be interpolated using the time and added to the image meta data (CCD.csv or imagefilename.json). I cannot find these variables anywhere yet. Is this on the to-do-list or did I misunderstand?

Linda

**Comment by local-minimum** [comment]
As we discussed it internally, if I remember correctly, it would be best if the rac-tool did not do this since it quite complicates the data-flow through the program (or at least the part of the program we've written thus far). We considered interpolating such data in a second step, perhaps automatically when all files have been uploaded to S3. But it's also a question of if such development should wait until we have the housekeeping data integrated. If that also should be interpolated the same way.

It of course depends on your needs and @OleMartinChristensen 

For now, if we are to add this feature, would it be true that it's always from within a single project that interpolation data is gathered? That is, e.g. a HTR.csv in the same directory as the CCD.csv? We would also need to know exactly which columns should be interpolated, and how.

**Comment by lindamegner** [comment]
OK, maybe you are right that it is better to wait until we have the platform data. There will be temperatures coming from there too which should be interpolated in exactly the same way. 
So I will use the code I have set up in Level 1 for this for the moment and we can discuss this later.

**Comment by local-minimum** [comment]
We'll return to this when we do the lvl 1 processing
