### ISSUE TITLE
Problem using rac extract on mulitple files

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/rac-extract-payload#153]
# rac extract v 2.7

This was investigated sorting datetimes and looking at first and last items.

Racfile download dates
EXP Dates in files

21st to 28th: 
EXP Date from 22-11-22 08:32:54 to 22-11-23 19.16:07:25.

25th to 28th:
EXP Date from 2022-11-24 00:01:20 to 2022-11-24 00:05:31.

26th to 28th:
EXP Date from 2022-11-24 18:06:05 to 2022-11-24 19:00:03.

Something wrong when reading in multiple files?

# To reproduce
Download all .rac data from OHB FTP server and try and run rac extract on all of them.

**Comment by skymandr** [comment]
@OleMartinChristensen Could you see if you can reproduce the problem with v0.2.6?

**Comment by OleMartinChristensen** [comment]
@skymandr we are unfortunatelly completelly swamped with test results, and do not have too much time to debug, but I'll see if we find time and let you know

**Comment by skymandr** [comment]
> @skymandr we are unfortunatelly completelly swamped with test results, and do not have too much time to debug, but I'll see if we find time and let you know

@OleMartinChristensen I think we can probably do it ourselves from your report, but I'm currently stuck on a computer with too little RAM, so it will have to wait until tomorrow. I suggest we look into it, and let you know if we need you to do or test anything.

What would, however, help with the above is if you could update the reproduce section of the issue with the exact commands you ran, if those are still in your terminal history. Not crucial, but helpful.

**Comment by OleMartinChristensen** [comment]
``` sh
rac --project tmp *.rac
```

**Comment by skymandr** [comment]
@OleMartinChristensen All right, we've looked into this a bit now. No fix, but we think we have a good lead on the problem.

There appears to be a stretch of files between the 24th and 27th November that contain severely corrupt JPEG-files. It seems that the rac extract tool handles some of these problems fine (`Corrupt JPEG data: bad Huffman code` and `Premature end of JPEG file` seem to be handled correctly) but at some point we encounter a problem so severe that the tool makes a hard crash without error output. It appears to occur directly after or at least near to (some variation of ) `Unsupported marker type 0x6b`, but the fact that it manages to print this (and sometimes a different error after it) before termination means that we can't be sure that this error is the actual cause.

Anyway, we think we have isolated the problem to the JPEG-reading routines, which should be enough to go on a proper bug-hunt.

EDIT: The problem seems to be as old as the tool, not something newly introduced. We will probably prioritise fixing it in the latest version only, unless you see a need for patching the 0.2.x-version as well.

**Comment by OleMartinChristensen** [comment]
ok, do what you think is best. Currently this is a very large bottleneck in our processing, since we cannot search the data in any meaningfull way and need to spend alot of time guessing on which rac file to exract. 

do you know roughly when we can either have a fix for this or an alternative system up running? I just want to know if I should but energy on finding a work around or not.

**Comment by skymandr** [comment]
> ok, do what you think is best. Currently this is a very large bottleneck in our processing, since we cannot search the data in any meaningfull way and need to spend alot of time guessing on which rac file to exract.
> 
> do you know roughly when we can either have a fix for this or an alternative system up running? I just want to know if I should but energy on finding a work around or not.

The files that I've found that have the errors are all from 24–27/11, so if you skip those for now, you should be fine. That being said, I have a pull request up now that fixes the error-handling, see #155. Should be built and ready around lunch time CET.

**Comment by OleMartinChristensen** [comment]
ok

**Comment by skymandr** [comment]
A release has been made and binaries should be here shortly: https://github.com/innosat-mats/rac-extract-payload/releases/tag/v1.1.1

Please see releasenotes for _v1.0.0_ and _v1.1.0_ for changes compared to _v0.2.7_: https://github.com/innosat-mats/rac-extract-payload/releases
