### ISSUE TITLE
Convert resistance to temperature

### ISSUE THREAD

**Issue by local-minimum** [innosat-mats/rac-extract-payload#17]
* Check with @OleMartinChristensen exactly which should be temperatures in PWR, HTR, CPRUA/B
* Produce temperatures (lookup table and linear interpolation says @skymandr is best)

**Comment by skymandr** [comment]
Rather @skymandr says linear interpolation is, looking at the data, quite good enough. It might be worth doing it in log(RT) space, however. If we go for polynomial approach, it should definitely be done in log(RT) vs T.

I found no reference to temperature for CPRUA/B in the specs, but see attatched file for values from datasheets for PWR and HTR.

[termistorer.py.txt](https://github.com/innosat-mats/rac-extract-payload/files/4493643/termistorer.py.txt)

**Comment by skymandr** [comment]
> Rather @skymandr says linear interpolation is, looking at the data, quite good enough. It might be worth doing it in log(RT) space, however. If we go for polynomial approach, it should definitely be done in log(RT) vs T.
> 
> I found no reference to temperature for CPRUA/B in the specs, but see attatched file for values from datasheets for PWR and HTR.
> 
> [termistorer.py.txt](https://github.com/innosat-mats/rac-extract-payload/files/4493643/termistorer.py.txt)

The data for the HTR thermistor is exactly the same as in the table in the AEZ ICD, that is to say it is not an independent measurement, but taken directly from the data sheet. The only differences are that the table in the ICD only goes to 80 ⁰C, whereas the data sheet list temperatures up to 255 ⁰C, and that the ICD table lists "read out values" (called D in the ICD and translated to a voltage through the stated formula) corresponding to the different resistances and temperatures. There is no corresponding table for the PWR thermistor in the ICD, but since they use the data sheet data for the HTR the same should be OK for the PWR.

it should be noted that the D->R mapping is not exactly the same as using the route through voltage, due to the granularity of D. Using the formulae, D=22 corresponds to R_NTC=954330, not 963000 as the table says. The reason for this is most likely that they have picked the D that comes closes to the tabulated R for use in the table. The conclusion is that using the tabulated D probably means a loss of precision compared to going through the voltage. I would therfore suggest giving the formulae precedence and making the same implementation for both PWR and HTR, using D->V->R->T, even though the HTR table lists a mapping from readout to temperature (_i.e._ D->T). Looking at the data, using linear interpolation in the step R->T should be good enough.

**Comment by skymandr** [comment]
@local-minimum suggested that @OleMartinChristensen might have something to add to the discussion above.

**Comment by OleMartinChristensen** [comment]
Hi, please call me @local-minimum @skymandr if you need input on this question
